#ifndef STOPWATCH_PRIVATE_H
#define STOPWATCH_PRIVATE_H

#include "state_machine_library.h"

#define STATE_CONTROL			0
#define STATE_TIMECOUNT			1
#define STATE_ALARMMANAGE		2
#define STATE_TIMEMODE			3
#define STATE_TIMESETMODE		4
#define STATE_ALARMMODE			5
#define STATE_STOPWATCHMODE		6
#define STATE_SETHOURS			7
#define STATE_SETMINUTES		8
#define STATE_SETALARMHOURS		9
#define STATE_SETALARMMINUTES	10
#define STATE_STOPWATCHOFF		11
#define STATE_STOPWATCHRUN		12
#define STATE_STOPWATCHPAUSED	13
#define STATE_RUNNING			14
#define STATE_SHOWLAP			15
#define STATE_ALARMOFF			16
#define STATE_ALARMON			17
#define STATE_QUIET				18
#define STATE_RINGING			19
#define STATE_WAITING_NEXT_ACT	20

#define STATE_NUM				21

#endif
